require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FansController do

  # This should return the minimal set of attributes required to create a valid
  # Fan. As you add validations to Fan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all fans as @fans" do
      fan = Fan.create! valid_attributes
      get :index
      assigns(:fans).should eq([fan])
    end
  end

  describe "GET show" do
    it "assigns the requested fan as @fan" do
      fan = Fan.create! valid_attributes
      get :show, :id => fan.id.to_s
      assigns(:fan).should eq(fan)
    end
  end

  describe "GET new" do
    it "assigns a new fan as @fan" do
      get :new
      assigns(:fan).should be_a_new(Fan)
    end
  end

  describe "GET edit" do
    it "assigns the requested fan as @fan" do
      fan = Fan.create! valid_attributes
      get :edit, :id => fan.id.to_s
      assigns(:fan).should eq(fan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fan" do
        expect {
          post :create, :fan => valid_attributes
        }.to change(Fan, :count).by(1)
      end

      it "assigns a newly created fan as @fan" do
        post :create, :fan => valid_attributes
        assigns(:fan).should be_a(Fan)
        assigns(:fan).should be_persisted
      end

      it "redirects to the created fan" do
        post :create, :fan => valid_attributes
        response.should redirect_to(Fan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fan as @fan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fan.any_instance.stub(:save).and_return(false)
        post :create, :fan => {}
        assigns(:fan).should be_a_new(Fan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fan.any_instance.stub(:save).and_return(false)
        post :create, :fan => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fan" do
        fan = Fan.create! valid_attributes
        # Assuming there are no other fans in the database, this
        # specifies that the Fan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => fan.id, :fan => {'these' => 'params'}
      end

      it "assigns the requested fan as @fan" do
        fan = Fan.create! valid_attributes
        put :update, :id => fan.id, :fan => valid_attributes
        assigns(:fan).should eq(fan)
      end

      it "redirects to the fan" do
        fan = Fan.create! valid_attributes
        put :update, :id => fan.id, :fan => valid_attributes
        response.should redirect_to(fan)
      end
    end

    describe "with invalid params" do
      it "assigns the fan as @fan" do
        fan = Fan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fan.any_instance.stub(:save).and_return(false)
        put :update, :id => fan.id.to_s, :fan => {}
        assigns(:fan).should eq(fan)
      end

      it "re-renders the 'edit' template" do
        fan = Fan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fan.any_instance.stub(:save).and_return(false)
        put :update, :id => fan.id.to_s, :fan => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fan" do
      fan = Fan.create! valid_attributes
      expect {
        delete :destroy, :id => fan.id.to_s
      }.to change(Fan, :count).by(-1)
    end

    it "redirects to the fans list" do
      fan = Fan.create! valid_attributes
      delete :destroy, :id => fan.id.to_s
      response.should redirect_to(fans_url)
    end
  end

end
