require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RolsController do

  # This should return the minimal set of attributes required to create a valid
  # Rol. As you add validations to Rol, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all rols as @rols" do
      rol = Rol.create! valid_attributes
      get :index
      assigns(:rols).should eq([rol])
    end
  end

  describe "GET show" do
    it "assigns the requested rol as @rol" do
      rol = Rol.create! valid_attributes
      get :show, :id => rol.id.to_s
      assigns(:rol).should eq(rol)
    end
  end

  describe "GET new" do
    it "assigns a new rol as @rol" do
      get :new
      assigns(:rol).should be_a_new(Rol)
    end
  end

  describe "GET edit" do
    it "assigns the requested rol as @rol" do
      rol = Rol.create! valid_attributes
      get :edit, :id => rol.id.to_s
      assigns(:rol).should eq(rol)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rol" do
        expect {
          post :create, :rol => valid_attributes
        }.to change(Rol, :count).by(1)
      end

      it "assigns a newly created rol as @rol" do
        post :create, :rol => valid_attributes
        assigns(:rol).should be_a(Rol)
        assigns(:rol).should be_persisted
      end

      it "redirects to the created rol" do
        post :create, :rol => valid_attributes
        response.should redirect_to(Rol.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rol as @rol" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rol.any_instance.stub(:save).and_return(false)
        post :create, :rol => {}
        assigns(:rol).should be_a_new(Rol)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rol.any_instance.stub(:save).and_return(false)
        post :create, :rol => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rol" do
        rol = Rol.create! valid_attributes
        # Assuming there are no other rols in the database, this
        # specifies that the Rol created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rol.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => rol.id, :rol => {'these' => 'params'}
      end

      it "assigns the requested rol as @rol" do
        rol = Rol.create! valid_attributes
        put :update, :id => rol.id, :rol => valid_attributes
        assigns(:rol).should eq(rol)
      end

      it "redirects to the rol" do
        rol = Rol.create! valid_attributes
        put :update, :id => rol.id, :rol => valid_attributes
        response.should redirect_to(rol)
      end
    end

    describe "with invalid params" do
      it "assigns the rol as @rol" do
        rol = Rol.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rol.any_instance.stub(:save).and_return(false)
        put :update, :id => rol.id.to_s, :rol => {}
        assigns(:rol).should eq(rol)
      end

      it "re-renders the 'edit' template" do
        rol = Rol.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rol.any_instance.stub(:save).and_return(false)
        put :update, :id => rol.id.to_s, :rol => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rol" do
      rol = Rol.create! valid_attributes
      expect {
        delete :destroy, :id => rol.id.to_s
      }.to change(Rol, :count).by(-1)
    end

    it "redirects to the rols list" do
      rol = Rol.create! valid_attributes
      delete :destroy, :id => rol.id.to_s
      response.should redirect_to(rols_url)
    end
  end

end
